version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5  
    allow:
      - dependency-name: "@tact-lang/compiler"
        versioning-strategy: "auto"
