name: Remove test domain

on:
  workflow_dispatch:
    inputs:
      domain:
        type: choice
        description: 'Select the test domain to remove'
        required: true
        options:
          - td-nature
          - td-book
          - td-art

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'testing'
    env:
      JOB_ENV: 'testing'
      APP_ENV: "${{ format('{0}{1}', 'testing-', github.event.inputs.domain) }}"
      APP_DOMAIN: "${{ format('{0}{1}', github.event.inputs.domain, vars.APP_DOMAIN_TESTING) }}"

    permissions:
      packages: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Apply AWS k8s config
        run: aws eks update-kubeconfig --name ${{ vars.AWS_CLUSTER }} --region ${{ vars.AWS_REGION }}

      - name: Remove ${{ vars.APP_NAME }} from Kubernetes
        if: ${{ env.JOB_ENV == 'testing' }}
        run: |
          helm uninstall ${{ vars.APP_NAME }} --namespace ${{ vars.APP_NAME }}-${{ env.APP_ENV }}
